version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
    depends_on:
      - redis
      - test-db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  test-db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test_db
    ports:
      - "5432:5432"

  tests:
    build: 
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
    depends_on:
      - test-db
    environment:
      - DATABASE_URL=postgresql://test:test@test-db:5432/test_db
      - TESTING=true